// generate-spells.js — parse design/spells.csv into a checked-in ES module.
//
// The canonical roster lives ONLY in design/spells.csv. This script is the
// single point that turns that CSV into browser/Node importable data so the
// numbers are never hand-duplicated. Run with: npm run gen:spells
//
// Output: shared/src/balance/spellData.generated.js  (DO NOT EDIT BY HAND)

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const CSV_PATH = join(ROOT, 'design', 'spells.csv');
const OUT_PATH = join(ROOT, 'shared', 'src', 'balance', 'spellData.generated.js');

// Minimal RFC-4180-ish CSV parser: handles quoted fields with embedded commas
// and doubled quotes. Returns an array of string arrays.
export function parseCsv(text) {
  const rows = [];
  let row = [];
  let field = '';
  let inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i++; }
        else inQuotes = false;
      } else {
        field += c;
      }
    } else if (c === '"') {
      inQuotes = true;
    } else if (c === ',') {
      row.push(field); field = '';
    } else if (c === '\r') {
      // ignore, newline handled by \n
    } else if (c === '\n') {
      row.push(field); field = '';
      rows.push(row); row = [];
    } else {
      field += c;
    }
  }
  if (field.length > 0 || row.length > 0) { row.push(field); rows.push(row); }
  return rows.filter((r) => r.length > 1 || (r.length === 1 && r[0].trim() !== ''));
}

const NUMERIC = new Set(['id', 'aether', 'charges', 'cooldown_s', 'min_cast_s', 'loadout_points']);
const BOOLEAN = new Set(['secret']);

export function rowsToSpells(rows) {
  const header = rows[0].map((h) => h.trim());
  const spells = [];
  for (let r = 1; r < rows.length; r++) {
    const cells = rows[r];
    const spell = {};
    for (let c = 0; c < header.length; c++) {
      const key = header[c];
      let val = (cells[c] ?? '').trim();
      if (NUMERIC.has(key)) spell[key] = Number(val);
      else if (BOOLEAN.has(key)) spell[key] = val.toLowerCase() === 'true';
      else spell[key] = val;
    }
    // Split the semicolon-delimited counter list into an array for tooling.
    spell.counterList = (spell.counters || '')
      .split(';')
      .map((s) => s.trim())
      .filter(Boolean);
    spells.push(spell);
  }
  return spells;
}

function checksumOf(csvText) {
  // Small stable FNV-1a checksum so a stale generated file is obvious in review.
  let h = 2166136261 >>> 0;
  for (let i = 0; i < csvText.length; i++) {
    h ^= csvText.charCodeAt(i);
    h = Math.imul(h, 16777619) >>> 0;
  }
  return h.toString(16).padStart(8, '0');
}

export function emitModule(spells, sourceChecksum) {
  const lines = [];
  lines.push('// AUTO-GENERATED by scripts/generate-spells.js — DO NOT EDIT BY HAND.');
  lines.push('// Source: design/spells.csv  (checksum ' + sourceChecksum + ')');
  lines.push('// Regenerate with: npm run gen:spells');
  lines.push('//');
  lines.push('// The full canonical 40-spell roster. Phase 1 exposes a curated 8-spell');
  lines.push('// starter loadout (see ./loadouts.js); the rest is data ready for');
  lines.push('// Phase 2/3 without re-typing any numbers.');
  lines.push('');
  lines.push('export const SPELLS_SOURCE_CHECKSUM = ' + JSON.stringify(sourceChecksum) + ';');
  lines.push('');
  lines.push('export const SPELL_CATALOG = [');
  for (const s of spells) {
    lines.push('  ' + JSON.stringify(s) + ',');
  }
  lines.push('];');
  lines.push('');
  lines.push('export const SPELLS_BY_ID = Object.freeze(');
  lines.push('  SPELL_CATALOG.reduce((m, s) => { m[s.id] = s; return m; }, {})');
  lines.push(');');
  lines.push('');
  lines.push('export const SPELLS_BY_NAME = Object.freeze(');
  lines.push('  SPELL_CATALOG.reduce((m, s) => { m[s.name] = s; return m; }, {})');
  lines.push(');');
  lines.push('');
  lines.push('export function getSpell(idOrName) {');
  lines.push('  return SPELLS_BY_ID[idOrName] || SPELLS_BY_NAME[idOrName] || null;');
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

export function generate() {
  const csvText = readFileSync(CSV_PATH, 'utf8');
  const rows = parseCsv(csvText);
  const spells = rowsToSpells(rows);
  const checksum = checksumOf(csvText);
  const module = emitModule(spells, checksum);
  return { module, spells, checksum };
}

const invokedDirectly =
  process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];

if (invokedDirectly) {
  const { module, spells, checksum } = generate();
  writeFileSync(OUT_PATH, module, 'utf8');
  console.log(`Generated ${spells.length} spells -> ${OUT_PATH} (checksum ${checksum})`);
}
